### PR TITLE
(WIP) Switch drawer to responsive type

### LINKED ISSUE #23: Update the drawer to use the responsive drawer type
https://material-ui.com/components/drawers/#responsive-drawer

I had this originally before initial launch, but changed it to the persistent drawer, but I think that was a mistake. It's annoying to have to open the drawer every time to navigate. 

Also mentioned here: https://www.reddit.com/r/swrpg/comments/f6nyyh/introducing_the_outer_rim_swrpg_stats_site_and/fi71a0d?utm_source=share&utm_medium=web2x

### PR DESCRIPTION
**Pull request by duffn**
Closes #23.

TODO
- [ ] Fix the width and layout on the tables.

### CODE REVIEW

**Comment by duffn** [comment]
Can you look at the table width specifically with this one? It's fine on larger screens, but on smaller ones, like a laptop, it seems to overflow the container since the drawer is always open.

**Comment by AndreLemay** [comment]
Yeah I see what you mean. Would probably need some css fiddling to get right, though I'm not sure I see the need for this.

Looking at the live site on mobile, when you open the drawer, the only difference is that the responsive one is drawn over top the table rather than pushing it aside, but the end result is the same in both cases. You have a drawer that takes up most of the screen and doesn't let you really interact with anything else until you do something with it.

**Comment by duffn** [comment]
Just noticed this though. That's one that needs fixing before merging.

Screen Shot 2020-02-29 at 12 28 33 PM

**Comment by AndreLemay** [comment]
Yeah that's what I saw as well, though it doesn't do that with the non-responsive drawer. I'm not sure what the benefit of the responsive one is, especially if it just adds extra work like this to something that's already functioning

**Comment by duffn** [comment]
I, and at least a few other users, have found it slightly annoying to constantly click on the hamburger when on desktop in order to navigate between resources.

It's not a top priority though, so I'm not going to spend too much time on it right now.

**Comment by AndreLemay** [comment]
Ah ok. Makes sense.

**Pull request closed without merging**
