### PR TITLE
Brawn melee display

### PR DESCRIPTION
**Pull request by AndreLemay**
Implements the display of a '+' in the damage column of any weapon table (including adversary and creature weapons) whenever that weapon's damage in enhanced by the character's brawn rating.

Note: This PR is only the implementation. While some newer data already includes this, all the old data still needs to be updated to include brawn: true || false

### CODE REVIEW

**Comment by duffn** [comment]
Looking good.

Is it possible to sort it so that the brawn items are all at the bottom (or top if sorted the other way) of the number. So,

1
1
+1
+1
2
2
+2
3

Right now, they are interspersed with the non-brawn numbers.

**Comment by AndreLemay** [comment]
Will need a custom sorter, but shouldn't be difficult

**Comment by AndreLemay** [comment]
So it's slightly weird because for whatever reason mui-datatables decided that the appropriate place for customized sorting is at the table level.

The upside I guess is that if we need to add custom sorting to any other columns, we just need to add an additional case to the existing switch.

**Comment by duffn** [comment]
This looks like it's sorting great, thanks.

Looking at the preview build on cloud, one weird thing is that we seem to now be missing the restricted price checkbox filters.

Screen Shot 2020-03-05 at 12 17 07 PM

**Comment by AndreLemay** [comment]
Oh? That's weird. I didn't touch those. Could be git borked the merge. I'll take a look at that.

**Comment by duffn** [comment]
Let's get this on as is and work on the rest after. I'm itching to get brawn done and get more data in.

This is good to ship as is, yes?

**Comment by AndreLemay** [comment]
Assuming you're good with not having the price filter, sure. I'm actually working on that now, so I should be able to have that ready relatively soon.

**Comment by duffn** [comment]
:shipit:

**Pull request merged**
