### PR TITLE
Add full site search

### LINKED ISSUE #66: Add full site search
It would be cool to have full site search capability.

Does one search for an item without going to the resource type first though? Maybe if it’s convenient and fast. Or maybe this is not very useful and just only cool?

Some resources:
- https://www.gatsbyjs.org/docs/adding-search/
- https://assortment.io/posts/gatsby-site-search-lunr-js

I love the toolbar search on the material UI site: https://material-ui.com/

### PR DESCRIPTION
**Pull request by duffn**
Closes #66.

This is a big one so only if you have the time, I would appreciate a quick review. I've been poking around at this a bit, so will probably merge either tonight or tomorrow. 

I'm excited about this one!

### CODE REVIEW

**Comment by AndreLemay** [comment]
I think it would be a better user experience to have a search field directly in the toolbar, like this:
https://material-ui.com/components/app-bar/#app-bar-with-a-primary-search-field

Then when they click the search icon or hit enter we could navigate to the existing search page with the query string pre-filled, and they could continue searching from there.

**Comment by AndreLemay** [comment]
The scrollbar also doesn't look that great when it pops up in the middle of the screen:
image

We already have a scrollbar on the right, I think we can just use that scrollbar and maybe stick the search bar to the top (would be unnecessary if we had it in the toolbar, then we wouldn't need the extra search field and could just show resources.

**Comment by AndreLemay** [comment]
Also, seems like if you type too quickly, some characters get lost. Really noticeable when running in dev mode locally (typed "blaster" quickly and got a search for "br"). Checked on the gatsby cloud build and I see the same there (though less pronounced, "blaster" turned into "baster").

**Comment by duffn** [comment]
> I think it would be a better user experience to have a search field directly in the toolbar, like this:
material-ui.com/components/app-bar/#app-bar-with-a-primary-search-field

Agreed! I wrote that in the issue and then completely didn't even do it.

> The scrollbar also doesn't look that great when it pops up in the middle of the screen:

Yeah, that doesn't look good. 

> Also, seems like if you type too quickly, some characters get lost. Really noticeable when running in dev mode locally (typed "blaster" quickly and got a search for "br"). Checked on the gatsby cloud build and I see the same there (though less pronounced, "blaster" turned into "baster").

I know. I need to find a way to slightly delay search or something along those lines.

**Comment by duffn** [comment]
I've pushed up changes for search in the app bar and for the search results height.

I'm playing around with the other ideas.

**Comment by duffn** [comment]
This most recent commit takes out the real-time search entirely and just relies on the search in the toolbar. 

I agree that the toolbar is better and I'm thinking that the real-time search was a novelty and is not worth the speed. It may be possible to speed it up, but would require some work on the underlying Gatsby plugin, which I'm not sure I want to dive into (we could potentially set all single letters as stop words, which would maybe speed it up http://elasticlunr.com/docs/stop_word_filter.js.html)

I'm inclined to do search like this now and exclude the real-time entirely.

**Comment by AndreLemay** [comment]
I haven't looked into the plugin itself, but for real time search, I think what we'd need to do is have the onChange event just update the component state with the current search string, and we'd then debounce the actual search call, that way the search results won't update until the user stops typing.

That aside, I noticed on the current cloud build, when you search you'll see the search page with a search for "" for a second before it shows the actually search. Haven't dug into how the search page itself works so I'm not 100% sure on what's causing it, but it looks like react is doing an initial render where it doesn't have the search query yet, does some async operation to get that and do the search, then re-renders with both. If we can, I think we should have the searchQuery show up from the start, then maybe we can have a message like "searching..." or a loading animation over the results section until it shows. Might also need to track when it's searching so we know whether to show "searching..." vs "no results".

**Comment by duffn** [comment]
I agree about the "Searching..." note.

For real-time, we can ship this version first and then work on that later if we decide it's necessary.

**Comment by duffn** [comment]
Added "Searching..." vs. results vs. no results.

**Comment by AndreLemay** [comment]
Looks great! Approved.

**Comment by duffn** [comment]
🎉

**Pull request merged**
