### PR TITLE
Add dark mode theme

### LINKED ISSUE #2: Add dark mode theme for the site
This is a user request to add a dark mode theme for the site: https://www.reddit.com/r/swrpg/comments/f6nyyh/introducing_the_outer_rim_swrpg_stats_site_and/fi68nff?utm_source=share&utm_medium=web2x

We'll want to keep the user's preference in between visits to the site.

## Examples

- Here's how the Material UI docs site does it: https://github.com/mui-org/material-ui/blob/master/docs/src/modules/components/ThemeContext.js
- Question about how to do it in MUI: https://spectrum.chat/material-ui/help/how-to-change-theme-on-the-fly~0d7d86d5-2753-4bf0-8c21-10e6de115805
- Example: https://codesandbox.io/s/toggle-theme-dark-light-v8xkq

### PR DESCRIPTION
**Pull request by duffn**
- ~~I moved all of the table styles to the top layout to easily handle theme creation, but may need some organization.~~
- I've removed the top layout.
- Saving light/dark mode in state.
- Lots of light/dark ternaries in the theme. Is there a better way to do this?
- Tweaked colors a bit for better display in both themes.
- ~~This seems to be quick except for the books pages. Check the opening and closing of the menu when on a books page. Can we correct this?~~
- This also stinks in dev mode.

Closes #2

### CODE REVIEW

**Comment by AndreLemay** [comment]
Code-wise I think it looks good. Moving all the styles to one place is helpful.

With regards to all the ternary statements, I'm not sure there's any other way of doing that besides just creating 2 style objects and choosing one or the other. Might be a good way to go if we put those off in their own file/function that takes in the theme string and returns the appropriate style object. Would also make it possible to have multiple themes if we ever wanted that.

For the drawer slowness... that's really weird to me. I have no idea how changing colours could cause that to be slower, but comparing the live site with the one on gatsby cloud, it looks like the drawer is slower overall, but most noticeable on the books page (probably because of how many tables there are). Only thing I could think of is that maybe building the style object with all the ternaries somehow slows it down.. but I really don't think a handful of them could be that noticeable. Might be worth trying it with React's profiling tools running to see what's going on.

**Comment by duffn** [comment]
Thanks for taking a look. 

I'll play around with it a little bit. The drawer slowness is not good and definitely needs to be fixed before shipping.

**Comment by duffn** [comment]
It's definitely because I've got the theme creation inside of the `TopLayout` component. I'll try to work on fixing it tomorrow.

**Comment by duffn** [comment]
I've made some wholesale changes here, but this is looking much better now speed wise. 

I took the theme provider from the material-ui.com site and tweaked it for our use. https://github.com/mui-org/material-ui/blob/dbc1aee89b2a50cf248683639e490caf1202f4b0/docs/src/modules/components/ThemeContext.js

Any additional thoughts?

**Comment by AndreLemay** [comment]
It definitely works a lot better now. I'm not sure the blue for the toolbar works that well in dark mode though, it's a little bright. Comparing this site (left) to the material-ui site (right)

Light theme:
image

Dark theme:
image

**Comment by duffn** [comment]
I agree. Here's whats getting built right now.

Screen Shot 2020-03-07 at 7 34 47 PM

**Comment by duffn** [comment]
Shipping it!

**Pull request merged**
