### PR TITLE
Change to ensure the name column is sticky.

### LINKED ISSUE #321: Category is pinned to left column in tables
From a user:

> I also notice that the "Category" column is the one that sticks to the side of your screen when scrolling over rather than the name of the item. At first glance, I notice it in the Vehicles and Starships sections, as I didn't see any other categories that needed to scroll over like that (though I didn't perform an exhaustive search). 

"Name" should be pinned to the left, not "Category".

### PR DESCRIPTION
**Pull request by wojciechsmigielskijr**
Fixed #321

### CODE REVIEW

**Comment by duffn** [comment]
Awesome, thanks for the contribution! I wonder if it's possible to pin the header as well during scrolling? The column itself is pinned, but the header is not.

Screen Shot 2023-01-01 at 8 32 36 AM

**Comment by wojciechsmigielskijr** [comment]
@duffn I did look into that however was not able to get it working sadly 😞. I'll take another look and see if I can make any other improvements, noticed today that the filters are not saved if you click on an item. Which could be beneficial, another solution would be to make clicking on items open in a new tab.

**Comment by duffn** [comment]
Thanks for your work here. I’d hold off on anything else for the moment as I evaluate a migration off of Gatsby. https://github.com/duffn/theouterrim/issues/374

**Comment by duffn** [comment]
This is no longer relevant after https://github.com/duffn/theouterrim/pull/363

**Pull request closed without merging**
