### PR TITLE
Move table toolbar to the left side

### LINKED ISSUE #211: Reposition table tools to the left of the header
See if we can reposition the table tools; i.e. search, filter, export, etc.; just to the right of the table title. They're all the way over to the far right of the header and if you have a wide table, annoying to get to.

### PR DESCRIPTION
**Pull request by AndreLemay**
- Move table toolbar to the left side
- Change to using theme breakpoint in override instead of ternary operator

Closes #211

### CODE REVIEW

**Comment by duffn** [comment]
Hmm, 🤔 

```
22:10:02 PM: 78 | }, themeInitialOptions) 79 | > 80 | const prefersDarkMode = useMediaQuery("(prefers-color-scheme: dark)") | ^ 81 | const preferredType = prefersDarkMode ? "dark" : "light" 82 | const { 83 | dense, WebpackError: ReferenceError: useMediaQuery is not defined - ThemeContext.js:80 ThemeProvider src/components/shared/ThemeContext.js:80:27
```

I wonder what happened here?

**Comment by AndreLemay** [comment]
That's my bad, didn't realize we were using useMediaQuery elsewhere in the file so I removed the import. Fixed now.

**Comment by duffn** [comment]
Looks like something went sideways with that last commit.

**Comment by AndreLemay** [comment]
Well that's weird... Somehow vscode undid the entire previous commit when I thought it only did a regular 'undo' that had put the import back..

**Comment by duffn** [comment]
When you click on the search icon, the search box is not usable. It looks like the search bar is trying to open up, but you can click on it to enter any text.

**Pull request merged**
