### PR TITLE
Dawn of Rebellion Species, Skills, and Talents added

### PR DESCRIPTION
**Pull request by alexholliz**

### CODE REVIEW

**Comment by duffn** [comment]
Excellent, thank you! I'll take a look. I've also added you to the index spreadsheet denoting that you'll be working on DoR. https://github.com/duffn/theouterrim/issues/1

**Comment by duffn** [comment]
This looks good to me. Thanks for updating the grammar errors as well. 

Can you please also note here that these sections are entered. https://github.com/duffn/theouterrim/blob/master/src/data/content-status.yaml

**Comment by johncoxon** [comment]
Hello, didn't know if there was a better place to put this but I've added the vehicles, adversaries and starships from Dawn of Rebellion up to page 35.

**Comment by duffn** [comment]
@johncoxon That's great, thanks! Can you add you name to the line for DoR here? I do believe we have 3 people working on the book now, so just want to make sure nobody ends up doing extra work. https://docs.google.com/spreadsheets/d/1NLgyvj_xCfOGdDGqqfX1xtOvjmucXA0J_8LVq5d4Tm4/edit#gid=0

**Comment by alexholliz** [comment]
@johncoxon Awesome! I had just finished Weapons, and was about to start in on Droids (Adversaries) but you've got that locked down.
@duffn should I mark those sections as complete in content-status.yml on my pr for weapons?

**Comment by johncoxon** [comment]
I've put myself down as my Discord username (Monotone#5163).

**Comment by duffn** [comment]
@johncoxon Oops, sorry! I saw that. I didn't realize you were one in the same. 

@alexholliz I like to mark them done in `content-status` with the actual PR that includes the data, so I can do that when we get those tabs in. Though I'm certainly not going to stop you if you want to do that yourself. 😄

**Pull request merged**
